//
//  RatingControl.swift
//  FoodTracker
//
//  Created by Kunal Dhingra on 2017-01-29.
//  Copyright © 2017 Kunal Dhingra. All rights reserved.
//

import UIKit

class RatingControl: UIStackView {
    
    //MARK: Initialization
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        setupButtons()
    }
    
    required init(coder: NSCoder) {
        super.init(coder: coder)
        setupButtons()
    }

    // MARK: Button Action
    
    func ratingButtonTapped(button: UIButton) {
        print("Button pressed 👍")
    }
    
    
    //MARK: Private Methods
    
    private func setupButtons() {
        
        // Create the button
        let button = UIButton()
        button.backgroundColor = UIColor.red
        
        // Add constraints
        
        // Remove the autogenerated constraints that define the view's size and position
        button.translatesAutoresizingMaskIntoConstraints = false
        
        // button’s heightAnchor and widthAnchor properties give access to layout anchors.
        // The anchor’s constraint(equalToConstant:) method returns a constraint that defines a constant height or width for the view
        // The constraint’s isActive property activates or deactivates the constraint. When you set this property to true, the system adds the constraint to the correct view, and activates it.      
        
        button.heightAnchor.constraint(equalToConstant: 44.0).isActive = true
        button.widthAnchor.constraint(equalToConstant: 44.0).isActive = true
        
        // Setup the button action
        button.addTarget(self, action: #selector(RatingControl.ratingButtonTapped(button:)), for: .touchUpInside)
        
        // Add the button to the stack
        addArrangedSubview(button)
    }
}
